### ISSUE TITLE
    run_cmd("hugo", "unable to build hugo site")

### ISSUE THREAD

**Issue by BlueBike538** [slspeek/odbinfo#1]
Does not work for me.
    run_cmd("hugo", "unable to build hugo site") what I see in log. 
OS is UBUNTI 20.04 
Lo version 6.4.7.2.

**Comment by slspeek** [comment]
Thank you for your interest in odbinfo. It was written and tested for LibreOffice 7.0. So I suggest you upgrade to LibreOffice 7.0.
